# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/frozenfoot/CLionProjects/tp-http-server

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/frozenfoot/CLionProjects/tp-http-server

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/frozenfoot/CLionProjects/tp-http-server/CMakeFiles /home/frozenfoot/CLionProjects/tp-http-server/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/frozenfoot/CLionProjects/tp-http-server/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named untitled

# Build rule for target.
untitled: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 untitled
.PHONY : untitled

# fast build rule for target.
untitled/fast:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/build
.PHONY : untitled/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/main.cpp.s
.PHONY : main.cpp.s

source/Handler.o: source/Handler.cpp.o

.PHONY : source/Handler.o

# target to build an object file
source/Handler.cpp.o:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/source/Handler.cpp.o
.PHONY : source/Handler.cpp.o

source/Handler.i: source/Handler.cpp.i

.PHONY : source/Handler.i

# target to preprocess a source file
source/Handler.cpp.i:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/source/Handler.cpp.i
.PHONY : source/Handler.cpp.i

source/Handler.s: source/Handler.cpp.s

.PHONY : source/Handler.s

# target to generate assembly for a file
source/Handler.cpp.s:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/source/Handler.cpp.s
.PHONY : source/Handler.cpp.s

source/HandlerTask.o: source/HandlerTask.cpp.o

.PHONY : source/HandlerTask.o

# target to build an object file
source/HandlerTask.cpp.o:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/source/HandlerTask.cpp.o
.PHONY : source/HandlerTask.cpp.o

source/HandlerTask.i: source/HandlerTask.cpp.i

.PHONY : source/HandlerTask.i

# target to preprocess a source file
source/HandlerTask.cpp.i:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/source/HandlerTask.cpp.i
.PHONY : source/HandlerTask.cpp.i

source/HandlerTask.s: source/HandlerTask.cpp.s

.PHONY : source/HandlerTask.s

# target to generate assembly for a file
source/HandlerTask.cpp.s:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/source/HandlerTask.cpp.s
.PHONY : source/HandlerTask.cpp.s

source/Server.o: source/Server.cpp.o

.PHONY : source/Server.o

# target to build an object file
source/Server.cpp.o:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/source/Server.cpp.o
.PHONY : source/Server.cpp.o

source/Server.i: source/Server.cpp.i

.PHONY : source/Server.i

# target to preprocess a source file
source/Server.cpp.i:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/source/Server.cpp.i
.PHONY : source/Server.cpp.i

source/Server.s: source/Server.cpp.s

.PHONY : source/Server.s

# target to generate assembly for a file
source/Server.cpp.s:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/source/Server.cpp.s
.PHONY : source/Server.cpp.s

source/ThreadPool.o: source/ThreadPool.cpp.o

.PHONY : source/ThreadPool.o

# target to build an object file
source/ThreadPool.cpp.o:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/source/ThreadPool.cpp.o
.PHONY : source/ThreadPool.cpp.o

source/ThreadPool.i: source/ThreadPool.cpp.i

.PHONY : source/ThreadPool.i

# target to preprocess a source file
source/ThreadPool.cpp.i:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/source/ThreadPool.cpp.i
.PHONY : source/ThreadPool.cpp.i

source/ThreadPool.s: source/ThreadPool.cpp.s

.PHONY : source/ThreadPool.s

# target to generate assembly for a file
source/ThreadPool.cpp.s:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/source/ThreadPool.cpp.s
.PHONY : source/ThreadPool.cpp.s

source/http.o: source/http.cpp.o

.PHONY : source/http.o

# target to build an object file
source/http.cpp.o:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/source/http.cpp.o
.PHONY : source/http.cpp.o

source/http.i: source/http.cpp.i

.PHONY : source/http.i

# target to preprocess a source file
source/http.cpp.i:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/source/http.cpp.i
.PHONY : source/http.cpp.i

source/http.s: source/http.cpp.s

.PHONY : source/http.s

# target to generate assembly for a file
source/http.cpp.s:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/source/http.cpp.s
.PHONY : source/http.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... untitled"
	@echo "... edit_cache"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... source/Handler.o"
	@echo "... source/Handler.i"
	@echo "... source/Handler.s"
	@echo "... source/HandlerTask.o"
	@echo "... source/HandlerTask.i"
	@echo "... source/HandlerTask.s"
	@echo "... source/Server.o"
	@echo "... source/Server.i"
	@echo "... source/Server.s"
	@echo "... source/ThreadPool.o"
	@echo "... source/ThreadPool.i"
	@echo "... source/ThreadPool.s"
	@echo "... source/http.o"
	@echo "... source/http.i"
	@echo "... source/http.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

